### ISSUE TITLE
Resolve private GitHub https access (~/.netrc file).

### ISSUE THREAD

**Issue by Syntactical01** [3mcloud/lambda-packager#24]
## Issue:

**Scenario:**:
- Trying to package a project that uses a `setup.py` which has a dependency from a private GitHub repository.

**Problem:** The follow DroneCI step fails because the pip installation fails saying it does not have access to the repository.
```yaml
  - name: build-deployment
    image: 3mcloud/lambda-packager:python-3.7
    pull: always
    depends_on: []
    environment:
      LAMBDA_CODE_DIR: ./src
      ARTIFACT_NAME: deployment.zip
```
But the following step works without issues.
```yaml
  - name: build-deployment
    image: 3mcloud/lambda-packager:python-3.7
    pull: always
    depends_on: []
    environment:
      LAMBDA_CODE_DIR: ./src
      ARTIFACT_NAME: deployment.zip
    commands:
    - /entrypoint.sh
```
The reason for this is in regards to when the volume mount happens. In the second scenario the `entrypoint.sh` script runs after the volume mount, in which case drone mounts `~/.netrc` which is used for GitHub access. In the first case, the `~/.netrc` file is not yet mounted when `CMD ["/entrypoint.sh"]` is run within the Docker image, thus there is not GitHub access for the clone to work.

We should switch to using environment variables to generate the `~/.netrc` file.
